src/Presentation/SmartStore.Web/Models/ShoppingCart/ButtonPaymentMethodModel.cs
using System.Collections.Generic;
using System.Web.Routing;
using SmartStore.Web.Framework.Mvc;

namespace SmartStore.Web.Models.ShoppingCart
{
	public partial class ButtonPaymentMethodModel : ModelBase
	{
		public ButtonPaymentMethodModel()
		{
			Items = new List<ButtonPaymentMethodItem>();
		}

		public IList<ButtonPaymentMethodItem> Items { get; set; }

		public partial class ButtonPaymentMethodItem
		{
			public string ActionName { get; set; }
			public string ControllerName { get; set; }
			public RouteValueDictionary RouteValues { get; set; }
		}
	}
}

src/Presentation/SmartStore.Web/Models/ShoppingCart/EstimateShippingModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Mvc;

namespace SmartStore.Web.Models.ShoppingCart
{
    public partial class EstimateShippingModel : ModelBase
    {
        public EstimateShippingModel()
        {
            ShippingOptions = new List<ShippingOptionModel>();
            Warnings = new List<string>();
            
            AvailableCountries = new List<SelectListItem>();
            AvailableStates = new List<SelectListItem>();
        }

        public bool Enabled { get; set; }

        public IList<ShippingOptionModel> ShippingOptions { get; set; }

        public IList<string> Warnings { get; set; }
        
        [SmartResourceDisplayName("ShoppingCart.EstimateShipping.Country")]
        public int? CountryId { get; set; }
        [SmartResourceDisplayName("ShoppingCart.EstimateShipping.StateProvince")]
        public int? StateProvinceId { get; set; }
        [SmartResourceDisplayName("ShoppingCart.EstimateShipping.ZipPostalCode")]
        public string ZipPostalCode { get; set; }

        public IList<SelectListItem> AvailableCountries { get; set; }
        public IList<SelectListItem> AvailableStates { get; set; }

		#region Nested Classes

        public partial class ShippingOptionModel : ModelBase
        {
            public string Name { get; set; }

            public string Description { get; set; }

            public string Price { get; set; }
        }

		#endregion
    }
}

src/Presentation/SmartStore.Web/Models/ShoppingCart/MiniShoppingCartModel.cs
using System.Collections.Generic;
using SmartStore.Core.Domain.Catalog;
using SmartStore.Web.Framework.Mvc;
using SmartStore.Web.Models.Media;

namespace SmartStore.Web.Models.ShoppingCart
{
    public partial class MiniShoppingCartModel : ModelBase
    {
        public MiniShoppingCartModel()
        {
            Items = new List<ShoppingCartItemModel>();
        }

        public IList<ShoppingCartItemModel> Items { get; set; }
        public int TotalProducts { get; set; }
        public string SubTotal { get; set; }
        public bool DisplayShoppingCartButton { get; set; }
        public bool DisplayCheckoutButton { get; set; }
        public bool CurrentCustomerIsGuest { get; set; }
        public bool AnonymousCheckoutAllowed { get; set; }
        public bool ShowProductImages { get; set; }
        public int ThumbSize { get; set; }
        public int IgnoredProductsCount { get; set; }


        #region Nested Classes

        public partial class ShoppingCartItemModel : EntityModelBase
        {
            public ShoppingCartItemModel()
            {
                Picture = new PictureModel();
                BundleItems = new List<ShoppingCartItemBundleItem>();
            }

            public int ProductId { get; set; }

            public string ProductName { get; set; }

            public string ProductSeName { get; set; }

            public int Quantity { get; set; }

            public string UnitPrice { get; set; }

            public string AttributeInfo { get; set; }

            public PictureModel Picture { get; set; }

            public IList<ShoppingCartItemBundleItem> BundleItems { get; set; }

        }

        public partial class ShoppingCartItemBundleItem : ModelBase 
        {
            public string PictureUrl { get; set; }
            public string ProductName { get; set; }
            public string ProductSeName { get; set; }
        }

        #endregion
    }
}

src/Presentation/SmartStore.Web/Models/ShoppingCart/OrderTotalsModel.cs
using System.Collections.Generic;
using SmartStore.Web.Framework.Mvc;

namespace SmartStore.Web.Models.ShoppingCart
{
    public partial class OrderTotalsModel : ModelBase
    {
        public OrderTotalsModel()
        {
            TaxRates = new List<TaxRate>();
            GiftCards = new List<GiftCard>();
        }
        public bool IsEditable { get; set; }

        public string SubTotal { get; set; }

        public string SubTotalDiscount { get; set; }
        public bool AllowRemovingSubTotalDiscount { get; set; }

        public string Shipping { get; set; }
        public bool RequiresShipping { get; set; }
        public string SelectedShippingMethod { get; set; }

        public string PaymentMethodAdditionalFee { get; set; }

        public string Tax { get; set; }
        public IList<TaxRate> TaxRates { get; set; }
        public bool DisplayTax { get; set; }
        public bool DisplayTaxRates { get; set; }
        public bool DisplayWeight { get; set; }
        
        public IList<GiftCard> GiftCards { get; set; }

        public string OrderTotalDiscount { get; set; }
        public bool AllowRemovingOrderTotalDiscount { get; set; }
        public int RedeemedRewardPoints { get; set; }
        public string RedeemedRewardPointsAmount { get; set; }
        public string OrderTotal { get; set; }
        public decimal Weight { get; set; }

        #region Nested classes

        public partial class TaxRate: ModelBase
        {
            public string Rate { get; set; }
            public string Value { get; set; }
			public string Label { get; set; }
        }

        public partial class GiftCard : EntityModelBase
        {
            public string CouponCode { get; set; }
            public string Amount { get; set; }
            public string Remaining { get; set; }
        }
        #endregion
    }
}

src/Presentation/SmartStore.Web/Models/ShoppingCart/WishlistEmailAFriendModel.cs
using System.Web.Mvc;
using FluentValidation.Attributes;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Mvc;
using SmartStore.Web.Validators.ShoppingCart;

namespace SmartStore.Web.Models.ShoppingCart
{
    [Validator(typeof(WishlistEmailAFriendValidator))]
    public partial class WishlistEmailAFriendModel : ModelBase
    {
        [AllowHtml]
        [SmartResourceDisplayName("Wishlist.EmailAFriend.FriendEmail")]
        public string FriendEmail { get; set; }

        [AllowHtml]
        [SmartResourceDisplayName("Wishlist.EmailAFriend.YourEmailAddress")]
        public string YourEmailAddress { get; set; }

        [AllowHtml]
        [SmartResourceDisplayName("Wishlist.EmailAFriend.PersonalMessage")]
        public string PersonalMessage { get; set; }

        public bool SuccessfullySent { get; set; }
        public string Result { get; set; }

        public bool DisplayCaptcha { get; set; }
    }
}

src/Presentation/SmartStore.Web/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using SmartStore.Core;
using SmartStore.Core.Domain.Common;
using SmartStore.Core.Domain.Customers;
using SmartStore.Core.Domain.Discounts;
using SmartStore.Core.Domain.Orders;
using SmartStore.Core.Domain.Payments;
using SmartStore.Core.Domain.Shipping;
using SmartStore.Core.Plugins;
using SmartStore.Services.Catalog;
using SmartStore.Services.Common;
using SmartStore.Services.Customers;
using SmartStore.Services.Directory;
using SmartStore.Services.Localization;
using SmartStore.Core.Logging;
using SmartStore.Services.Orders;
using SmartStore.Services.Payments;
using SmartStore.Services.Shipping;
using SmartStore.Services.Tax;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Security;
using SmartStore.Web.Models.Checkout;
using SmartStore.Web.Models.Common;
using SmartStore.Services.Configuration;
using SmartStore.Web.Framework.Plugins;
using SmartStore.Web.Models.ShoppingCart;

namespace SmartStore.Web.Controllers
{
    [RequireHttpsByConfigAttribute(SslRequirement.Yes)]
    public partial class CheckoutController : PublicControllerBase
    {
		#region Fields

        private readonly IWorkContext _workContext;
		private readonly IStoreContext _storeContext;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly ILocalizationService _localizationService;
        private readonly ITaxService _taxService;
        private readonly ICurrencyService _currencyService;
        private readonly IPriceFormatter _priceFormatter;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly ICustomerService _customerService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly ICountryService _countryService;
        private readonly IStateProvinceService _stateProvinceService;
        private readonly IShippingService _shippingService;
        private readonly IPaymentService _paymentService;
        private readonly IOrderTotalCalculationService _orderTotalCalculationService;
        private readonly IOrderService _orderService;
        private readonly IWebHelper _webHelper;
        private readonly HttpContextBase _httpContext;
        private readonly IMobileDeviceHelper _mobileDeviceHelper;
		private readonly ISettingService _settingService;

        private readonly OrderSettings _orderSettings;
        private readonly RewardPointsSettings _rewardPointsSettings;
        private readonly PaymentSettings _paymentSettings;
        private readonly AddressSettings _addressSettings;
        private readonly ShoppingCartSettings _shoppingCartSettings;
		private readonly PluginMediator _pluginMediator;

        #endregion

		#region Constructors

		public CheckoutController(IWorkContext workContext, IStoreContext storeContext,
            IShoppingCartService shoppingCartService, ILocalizationService localizationService, 
            ITaxService taxService, ICurrencyService currencyService, 
            IPriceFormatter priceFormatter, IOrderProcessingService orderProcessingService,
            ICustomerService customerService,  IGenericAttributeService genericAttributeService,
            ICountryService countryService,
            IStateProvinceService stateProvinceService, IShippingService shippingService,
			IPaymentService paymentService, 
			IOrderTotalCalculationService orderTotalCalculationService,
            IOrderService orderService, IWebHelper webHelper,
            HttpContextBase httpContext, IMobileDeviceHelper mobileDeviceHelper,
            OrderSettings orderSettings, RewardPointsSettings rewardPointsSettings,
            PaymentSettings paymentSettings, AddressSettings addressSettings,
            ShoppingCartSettings shoppingCartSettings,
			ISettingService settingService,
			PluginMediator pluginMediator)
        {
            this._workContext = workContext;
			this._storeContext = storeContext;
            this._shoppingCartService = shoppingCartService;
            this._localizationService = localizationService;
            this._taxService = taxService;
            this._currencyService = currencyService;
            this._priceFormatter = priceFormatter;
            this._orderProcessingService = orderProcessingService;
            this._customerService = customerService;
            this._genericAttributeService = genericAttributeService;
            this._countryService = countryService;
            this._stateProvinceService = stateProvinceService;
            this._shippingService = shippingService;
            this._paymentService = paymentService;
            this._orderTotalCalculationService = orderTotalCalculationService;
            this._orderService = orderService;
            this._webHelper = webHelper;
            this._httpContext = httpContext;
            this._mobileDeviceHelper = mobileDeviceHelper;
			this._settingService = settingService;

            this._orderSettings = orderSettings;
            this._rewardPointsSettings = rewardPointsSettings;
            this._paymentSettings = paymentSettings;
            this._addressSettings = addressSettings;
            this._shoppingCartSettings = shoppingCartSettings;
			this._pluginMediator = pluginMediator;
        }

        #endregion

        #region Utilities

        [NonAction]
		protected bool IsPaymentWorkflowRequired(IList<OrganizedShoppingCartItem> cart, bool ignoreRewardPoints = false)
        {
            //check whether order total equals zero
            decimal? shoppingCartTotalBase = _orderTotalCalculationService.GetShoppingCartTotal(cart, ignoreRewardPoints);
            if (shoppingCartTotalBase.HasValue && shoppingCartTotalBase.Value == decimal.Zero)
                return false;

			if (_httpContext.GetCheckoutState().IsPaymentSelectionSkipped)
				return false;

            return true;
        }

        [NonAction]
        protected CheckoutBillingAddressModel PrepareBillingAddressModel(int? selectedCountryId = null)
        {
            var model = new CheckoutBillingAddressModel();
            //existing addresses
            var addresses = _workContext.CurrentCustomer.Addresses.Where(a => a.Country == null || a.Country.AllowsBilling).ToList();
            foreach (var address in addresses)
            {
                var addressModel = new AddressModel();
                addressModel.PrepareModel(address, 
                    false, 
                    _addressSettings);
                model.ExistingAddresses.Add(addressModel);
            }

            //new address
            model.NewAddress.CountryId = selectedCountryId;
            model.NewAddress.PrepareModel(null,
                false,
                _addressSettings,
                _localizationService,
                _stateProvinceService,
                () => _countryService.GetAllCountriesForBilling());
            return model;
        }

        [NonAction]
        protected CheckoutShippingAddressModel PrepareShippingAddressModel(int? selectedCountryId = null)
        {
            var model = new CheckoutShippingAddressModel();
            //existing addresses
            var addresses = _workContext.CurrentCustomer.Addresses.Where(a => a.Country == null || a.Country.AllowsShipping).ToList();
            foreach (var address in addresses)
            {
                var addressModel = new AddressModel();
                addressModel.PrepareModel(address,
                    false,
                    _addressSettings);
                model.ExistingAddresses.Add(addressModel);
            }

            //new address
            model.NewAddress.CountryId = selectedCountryId;
            model.NewAddress.PrepareModel(null,
                false,
                _addressSettings,
                _localizationService,
                _stateProvinceService,
                () => _countryService.GetAllCountriesForShipping());
            return model;
        }

		[NonAction]
		protected CheckoutShippingMethodModel PrepareShippingMethodModel(IList<OrganizedShoppingCartItem> cart)
		{
			var model = new CheckoutShippingMethodModel();

			var getShippingOptionResponse = _shippingService.GetShippingOptions(cart, _workContext.CurrentCustomer.ShippingAddress, "", _storeContext.CurrentStore.Id);

			if (getShippingOptionResponse.Success)
			{
				//performance optimization. cache returned shipping options.
				//we'll use them later (after a customer has selected an option).
				_genericAttributeService.SaveAttribute(_workContext.CurrentCustomer,
					SystemCustomerAttributeNames.OfferedShippingOptions, getShippingOptionResponse.ShippingOptions, _storeContext.CurrentStore.Id);

				var shippingMethods = _shippingService.GetAllShippingMethods();

				foreach (var shippingOption in getShippingOptionResponse.ShippingOptions)
				{
					var soModel = new CheckoutShippingMethodModel.ShippingMethodModel()
					{
						Name = shippingOption.Name,
						Description = shippingOption.Description,
						ShippingRateComputationMethodSystemName = shippingOption.ShippingRateComputationMethodSystemName,
					};

					var srcmProvider = _shippingService.LoadShippingRateComputationMethodBySystemName(shippingOption.ShippingRateComputationMethodSystemName);
					if (srcmProvider != null)
					{
						soModel.BrandUrl = _pluginMediator.GetBrandImageUrl(srcmProvider.Metadata);
					}

					//adjust rate
					Discount appliedDiscount = null;
					var shippingTotal = _orderTotalCalculationService.AdjustShippingRate(
						shippingOption.Rate, cart, shippingOption.Name, shippingMethods, out appliedDiscount);

					decimal rateBase = _taxService.GetShippingPrice(shippingTotal, _workContext.CurrentCustomer);
					decimal rate = _currencyService.ConvertFromPrimaryStoreCurrency(rateBase, _workContext.WorkingCurrency);
					soModel.FeeRaw = rate;

src/Presentation/SmartStore.Web/Views/ShoppingCart/Cart.Mobile.cshtml
@model ShoppingCartModel
@using SmartStore.Core.Domain.Orders;
@using SmartStore.Web.Models.Checkout;
@using SmartStore.Web.Models.ShoppingCart;
@{
    Layout = "~/Views/Shared/_Root.cshtml";

    //title
    Html.AddTitleParts(T("PageTitle.ShoppingCart").Text);
}
<div class="page shopping-cart-page">
    <div class="page-title">
        <h1>@T("ShoppingCart")</h1>
    </div>
    <div class="page-body">
        @Html.Partial("OrderSummary", Model)
    </div>
</div>

src/Presentation/SmartStore.Web/Views/ShoppingCart/Cart.cshtml
@model ShoppingCartModel
@using SmartStore.Core.Domain.Orders
@using SmartStore.Web.Models.Checkout
@using SmartStore.Web.Models.ShoppingCart;
@{
    Layout = "~/Views/Shared/_ColumnsOne.cshtml";
    
    Html.AddBodyCssClass("order-summary-page");
    
    //title
    Html.AddTitleParts(T("PageTitle.ShoppingCart").Text);
}
@Html.Action("CheckoutProgress", "Checkout", new { step = CheckoutProgressStep.Cart })
<div class="page shopping-cart-page">
    <div class="page-title">
        <h1>@T("ShoppingCart")</h1>
    </div>
    <div class="page-body">
        @Html.Partial("OrderSummary", Model)
    </div>
</div>

src/Presentation/SmartStore.Web/Views/ShoppingCart/EmailWishlist.Mobile.cshtml
@model WishlistEmailAFriendModel
@using SmartStore.Web.Models.ShoppingCart;
@{
    Layout = "~/Views/Shared/_Root.cshtml";

    //title
    Html.AddTitleParts(T("PageTitle.WishlistEmailAFriend").Text);
}
<div class="page email-a-friend-page">
    <div class="page-title">
        <h1>@T("Wishlist.EmailAFriend.Title")</h1>
    </div>
    <div class="page-body">
        @if (Model.SuccessfullySent)
        {
            <div class="result">
                @Model.Result
            </div>
        }
        else
        {
            <div class="send-email">
                @using (Html.BeginForm())
                {
                    <div class="message-error">
                        @Html.ValidationSummary(true)
                    </div>
                    <div>
                        @Html.LabelFor(model => model.FriendEmail)
                        @Html.TextBoxFor(model => model.FriendEmail, new { @class = "friend-email" })
                        @Html.ValidationMessageFor(model => model.FriendEmail)
                    </div>
                    <div>
                        @Html.LabelFor(model => model.YourEmailAddress)
                        @Html.TextBoxFor(model => model.YourEmailAddress, new { @class = "your-email" })
                        @Html.ValidationMessageFor(model => model.YourEmailAddress)
                    </div>
                    <div>
                        @Html.LabelFor(model => model.PersonalMessage)
                        @Html.TextAreaFor(model => model.PersonalMessage, new { @class = "personal-message" })
                        @Html.ValidationMessageFor(model => model.PersonalMessage)
                    </div>
                    if (Model.DisplayCaptcha)
                    {
                    <div class="captcha-box">
                        @Html.Raw(Html.GenerateCaptcha())
                    </div>
                    }
                    <div class="buttons">
                        <input type="submit" name="send-email" value="@T("Wishlist.EmailAFriend.Button")" />
                    </div>
                }
            </div>
        }
    </div>
</div>

src/Presentation/SmartStore.Web/Views/ShoppingCart/_CommentBox.Mobile.cshtml
@model ShoppingCartModel
@using SmartStore.Web.Models.ShoppingCart;
@if (Model.DisplayCommentBox)
{
    <div class="comment-box">
        <div class="title"><strong>@T("ShoppingCart.CommentBox")</strong></div>
        
        @Html.TextAreaFor(model => model.CustomerComment, new { placeholder = "Optional" })
    </div>
}

src/Presentation/SmartStore.Web/Views/ShoppingCart/_CommentBox.cshtml
@model ShoppingCartModel
@using SmartStore.Web.Models.ShoppingCart;

<div class="block block-bordered comment-box">

    <div class="block-title">@T("ShoppingCart.CommentBox")</div>

    <div class="block-body">

        @Html.TextAreaFor(model => model.CustomerComment, new { placeholder = "Optional" })

    </div>
</div>

src/Presentation/SmartStore.Web/Views/ShoppingCart/_OrderReviewData.cshtml
@model ShoppingCartModel.OrderReviewDataModel
@using SmartStore.Web.Models.ShoppingCart;
@if (Model.Display)
{
    <div class="order-review-data-box">
        <div class="row-fluid">

            <div class="billinginfo span12">
                <div class="block block-bordered">
                    <div class="block-title">
                        <span>@T("Order.BillingAddress")</span>
                        <a class="change-checkout-data pull-right" href='@Url.Action("BillingAddress", "Checkout")'>@T("Common.Change")</a>
                    </div>
                    <div class="block-body">
                        <div class="name">
                            @Model.BillingAddress.FirstName @Model.BillingAddress.LastName
                        </div>
                        <div class="email">
                            @T("Order.Email"): @Model.BillingAddress.Email
                        </div>
                        @if (Model.BillingAddress.PhoneEnabled)
                        {
                            <div class="phone">
                                @T("Order.Phone"): @Model.BillingAddress.PhoneNumber
                            </div>
                        }
                        @if (Model.BillingAddress.FaxEnabled)
                        {
                            <div class="fax">
                                @T("Order.Fax"): @Model.BillingAddress.FaxNumber
                            </div>
                        }
                        @if (Model.BillingAddress.CompanyEnabled && !String.IsNullOrEmpty(Model.BillingAddress.Company))
                        {
                            <div class="company">
                                @Model.BillingAddress.Company
                            </div>
                        }
                        @if (Model.BillingAddress.StreetAddressEnabled)
                        {
                            <div class="address1">
                                @Model.BillingAddress.Address1
                            </div>
                        }
                        @if (Model.BillingAddress.StreetAddress2Enabled && !String.IsNullOrEmpty(Model.BillingAddress.Address2))
                        {
                            <div class="address2">
                                @Model.BillingAddress.Address2
                            </div>
                        }
                        @if (Model.BillingAddress.CityEnabled ||
                            Model.BillingAddress.StateProvinceEnabled ||
                            Model.BillingAddress.ZipPostalCodeEnabled)
                        {
                            <div class="city-state-zip">
                                @if (Model.BillingAddress.CityEnabled)
                                {
                                    @Model.BillingAddress.City
                                }
                                @if (Model.BillingAddress.CityEnabled && (Model.BillingAddress.StateProvinceEnabled || Model.BillingAddress.ZipPostalCodeEnabled))
                                {
                                    <text>,</text>
                                }
                                @if (Model.BillingAddress.StateProvinceEnabled)
                                {
                                    @Model.BillingAddress.StateProvinceName
                                }
                                @if (Model.BillingAddress.ZipPostalCodeEnabled)
                                {
                                    @Model.BillingAddress.ZipPostalCode
                                }
                            </div>
                        }
                        @if (Model.BillingAddress.CountryEnabled && !String.IsNullOrEmpty(Model.BillingAddress.CountryName))
                        {
                            <div class="country">
                                @Model.BillingAddress.CountryName
                            </div>
                        }
                        </div>
                </div>
            </div>
            @if (Model.IsShippable)
            {
                <div class="shippinginfo span12">
                    <div class="block block-bordered">
                        <div class="block-title">
                            <span>@T("Order.ShippingAddress")</span>
                            <a class="change-checkout-data pull-right" href='@Url.Action("ShippingAddress", "Checkout")'>@T("Common.Change")</a>
                        </div>
                        <div class="block-body">
                            <div class="name">
                                @Model.ShippingAddress.FirstName @Model.ShippingAddress.LastName
                            </div>
                            <div class="email">
                                @T("Order.Email"): @Model.ShippingAddress.Email
                            </div>
                            @if (Model.ShippingAddress.PhoneEnabled)
                            {
                                <div class="phone">
                                    @T("Order.Phone"): @Model.ShippingAddress.PhoneNumber
                                </div>
                            }
                            @if (Model.ShippingAddress.FaxEnabled)
                            {
                                <div class="fax">
                                    @T("Order.Fax"): @Model.ShippingAddress.FaxNumber
                                </div>
                            }
                            @if (Model.ShippingAddress.CompanyEnabled && !String.IsNullOrEmpty(Model.ShippingAddress.Company))
                            {
                                <div class="company">
                                    @Model.ShippingAddress.Company
                                </div>
                            }
                            @if (Model.ShippingAddress.StreetAddressEnabled)
                            {
                                <div class="address1">
                                    @Model.ShippingAddress.Address1
                                </div>
                            }
                            @if (Model.ShippingAddress.StreetAddress2Enabled && !String.IsNullOrEmpty(Model.ShippingAddress.Address2))
                            {
                                <div class="address2">
                                    @Model.ShippingAddress.Address2
                                </div>
                            }
                            @if (Model.ShippingAddress.CityEnabled ||
                            Model.ShippingAddress.StateProvinceEnabled ||
                            Model.ShippingAddress.ZipPostalCodeEnabled)
                            {
                                <div class="city-state-zip">
                                    @if (Model.ShippingAddress.CityEnabled)
                                    {
                                        @Model.ShippingAddress.City
                                    }
                                    @if (Model.ShippingAddress.CityEnabled && (Model.ShippingAddress.StateProvinceEnabled || Model.ShippingAddress.ZipPostalCodeEnabled))
                                    {
                                        <text>,</text>
                                    }
                                    @if (Model.ShippingAddress.StateProvinceEnabled)
                                    {
                                        @Model.ShippingAddress.StateProvinceName
                                    }
                                    @if (Model.ShippingAddress.ZipPostalCodeEnabled)
                                    {
                                        @Model.ShippingAddress.ZipPostalCode
                                    }
                                </div>
                            }
                            @if (Model.ShippingAddress.CountryEnabled && !String.IsNullOrEmpty(Model.ShippingAddress.CountryName))
                            {
                                <div class="country">
                                    @Model.ShippingAddress.CountryName
                                </div>
                            }
                                </div>
                    </div>
                </div>
            }

        </div>

        @if (!String.IsNullOrEmpty(Model.PaymentMethod))
        {
            <div class="payment-method">
                <div class="block block-bordered">
                    <div class="block-title">
                        <span>@T("Order.PaymentMethod")</span>
						@if (!Model.IsPaymentSelectionSkipped)
						{
							<a class="change-checkout-data pull-right" href='@Url.Action("PaymentMethod", "Checkout")'>@T("Common.Change")</a>
						}
                    </div>
                    <div class="block-body">
                        @Model.PaymentMethod
						@if (Model.PaymentSummary.HasValue())
						{
							<span class="muted">@Model.PaymentSummary</span>
						}
                    </div>
                </div>
            </div>
        }

        @if (!String.IsNullOrEmpty(Model.ShippingMethod))
        {
            <div class="shipping-method">
                <div class="block block-bordered">
                    <div class="block-title">
                        <span>@T("Order.ShippingMethod")</span>
						<a class="change-checkout-data pull-right" href='@Url.Action("ShippingMethod", "Checkout")'>@T("Common.Change")</a>
                    </div>
                    <div class="block-body">
                        @Model.ShippingMethod
                    </div>
                </div>
            </div>
        }

    </div>
}