src/Presentation/SmartStore.Web/Administration/Controllers/LanguageController.cs
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using SmartStore.Admin.Models.Localization;
using SmartStore.Core;
using SmartStore.Core.Domain.Common;
using SmartStore.Core.Domain.Localization;
using SmartStore.Core.Plugins;
using SmartStore.Services.Localization;
using SmartStore.Services.Security;
using SmartStore.Services.Stores;
using SmartStore.Web.Framework;
using SmartStore.Web.Framework.Controllers;
using SmartStore.Web.Framework.Mvc;
using Telerik.Web.Mvc;
using System.Collections.Generic;
using SmartStore.Core.Data;

namespace SmartStore.Admin.Controllers
{
    [AdminAuthorize]
    public partial class LanguageController : AdminControllerBase
    {
        #region Fields

        private readonly ILanguageService _languageService;
        private readonly ILocalizationService _localizationService;
		private readonly IStoreService _storeService;
		private readonly IStoreMappingService _storeMappingService;
        private readonly IPermissionService _permissionService;
        private readonly IWebHelper _webHelper;
        private readonly AdminAreaSettings _adminAreaSettings;
		private readonly IPluginFinder _pluginFinder;

        #endregion

        #region Constructors

        public LanguageController(ILanguageService languageService,
            ILocalizationService localizationService,
			IStoreService storeService,
			IStoreMappingService storeMappingService,
            IPermissionService permissionService,
            IWebHelper webHelper,
            AdminAreaSettings adminAreaSettings,
			IPluginFinder pluginFinder)
        {
            this._localizationService = localizationService;
            this._languageService = languageService;
			this._storeService = storeService;
			this._storeMappingService = storeMappingService;
            this._permissionService = permissionService;
            this._webHelper = webHelper;
            this._adminAreaSettings = adminAreaSettings;
			this._pluginFinder = pluginFinder;
        }

        #endregion 
        #region Utilities

        [NonAction]
        private void PrepareFlagsModel(LanguageModel model)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            model.FlagFileNames = System.IO.Directory
                .EnumerateFiles(_webHelper.MapPath("~/Content/Images/flags/"), "*.png", SearchOption.TopDirectoryOnly)
                .Select(System.IO.Path.GetFileName)
                .ToList();
        }

		[NonAction]
		private void PrepareStoresMappingModel(LanguageModel model, Language language, bool excludeProperties)
		{
			if (model == null)
				throw new ArgumentNullException("model");

			model.AvailableStores = _storeService
				.GetAllStores()
				.Select(s => s.ToModel())
				.ToList();
			if (!excludeProperties)
			{
				if (language != null)
				{
					model.SelectedStoreIds = _storeMappingService.GetStoresIdsWithAccess(language);
				}
				else
				{
					model.SelectedStoreIds = new int[0];
				}
			}
		}

		[NonAction]
		protected void SaveStoreMappings(Language language, LanguageModel model)
		{
			var existingStoreMappings = _storeMappingService.GetStoreMappings(language);
			var allStores = _storeService.GetAllStores();
			foreach (var store in allStores)
			{
				if (model.SelectedStoreIds != null && model.SelectedStoreIds.Contains(store.Id))
				{
					//new role
					if (existingStoreMappings.Where(sm => sm.StoreId == store.Id).Count() == 0)
						_storeMappingService.InsertStoreMapping(language, store.Id);
				}
				else
				{
					//removed role
					var storeMappingToDelete = existingStoreMappings.Where(sm => sm.StoreId == store.Id).FirstOrDefault();
					if (storeMappingToDelete != null)
						_storeMappingService.DeleteStoreMapping(storeMappingToDelete);
				}
			}
		}

        #endregion

        #region Languages

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageLanguages))
                return AccessDeniedView();

            var languages = _languageService.GetAllLanguages(true);
            var gridModel = new GridModel<LanguageModel>
            {
                Data = languages.Select(x => x.ToModel()),
                Total = languages.Count()
            };
            return View(gridModel);
        }

        [HttpPost, GridAction(EnableCustomBinding = true)]
        public ActionResult List(GridCommand command)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageLanguages))
                return AccessDeniedView();

            var languages = _languageService.GetAllLanguages(true);
            var gridModel = new GridModel<LanguageModel>
            {
                Data = languages.Select(x => x.ToModel()),
                Total = languages.Count()
            };
            return new JsonResult
            {
                Data = gridModel
            };
        }

        public ActionResult Create()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageLanguages))
                return AccessDeniedView();

            var model = new LanguageModel();
            //flags
            PrepareFlagsModel(model);
			//Stores
			PrepareStoresMappingModel(model, null, false);
            //default values
            //model.Published = true;
            return View(model);
        }

        [HttpPost, ParameterBasedOnFormNameAttribute("save-continue", "continueEditing")]
        public ActionResult Create(LanguageModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageLanguages))
                return AccessDeniedView();

            if (ModelState.IsValid)
            {
                var language = model.ToEntity();
                _languageService.InsertLanguage(language);

				//Stores
				SaveStoreMappings(language, model);

				var plugins = _pluginFinder.GetPluginDescriptors(true);
				var filterLanguages = new List<Language>() { language };

				foreach (var plugin in plugins)
				{
					_localizationService.ImportPluginResourcesFromXml(plugin, null, false, filterLanguages);
				}

                NotifySuccess(_localizationService.GetResource("Admin.Configuration.Languages.Added"));
                return continueEditing ? RedirectToAction("Edit", new { id = language.Id }) : RedirectToAction("List");
            }

            //flags
            PrepareFlagsModel(model);
			//Stores
			PrepareStoresMappingModel(model, null, true);

            //If we got this far, something failed, redisplay form
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageLanguages))
                return AccessDeniedView();

            var language = _languageService.GetLanguageById(id);
            if (language == null)
                //No language found with the specified id
                return RedirectToAction("List");

            //set page timeout to 5 minutes
            this.Server.ScriptTimeout = 300;

            var model = language.ToModel();

            //flags
            PrepareFlagsModel(model);
			//Stores
			PrepareStoresMappingModel(model, language, false);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormNameAttribute("save-continue", "continueEditing")]
        public ActionResult Edit(LanguageModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageLanguages))
                return AccessDeniedView();

            var language = _languageService.GetLanguageById(model.Id);
            if (language == null)
                //No language found with the specified id
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                //ensure we have at least one published language
                var allLanguages = _languageService.GetAllLanguages();
                if (allLanguages.Count == 1 && allLanguages[0].Id == language.Id &&
                    !model.Published)
                {
					NotifyError("At least one published language is required.");
                    return RedirectToAction("Edit", new { id = language.Id });
                }

                //update
                language = model.ToEntity(language);
                _languageService.UpdateLanguage(language);

				//Stores
				SaveStoreMappings(language, model);

                //notification
                NotifySuccess(_localizationService.GetResource("Admin.Configuration.Languages.Updated"));
                return continueEditing ? RedirectToAction("Edit", new { id = language.Id }) : RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            //flags
            PrepareFlagsModel(model);
			//Stores
			PrepareStoresMappingModel(model, language, true);

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageLanguages))
                return AccessDeniedView();

            var language = _languageService.GetLanguageById(id);
            if (language == null)
                //No language found with the specified id
                return RedirectToAction("List");

            //ensure we have at least one published language
            var allLanguages = _languageService.GetAllLanguages();
            if (allLanguages.Count == 1 && allLanguages[0].Id == language.Id)
            {
				NotifyError("At least one published language is required.");
                return RedirectToAction("Edit", new { id = language.Id });
            }

src/Presentation/SmartStore.Web/Administration/Views/Language/Create.cshtml
@model LanguageModel
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Languages.AddNew").Text;
}
@using (Html.BeginForm())
{
    <div class="section-header">
        <div class="title">
            @T("Admin.Configuration.Languages.AddNew") @Html.ActionLink("(" + T("Admin.Configuration.Languages.BackToList") + ")", "List")
        </div>
        <div class="options">
            <button type="submit" name="save" value="save" class="btn btn-primary"><i class="fa fa-check"></i>&nbsp;@T("Admin.Common.Save")</button>
            <button type="submit" name="save" value="save-continue" class="btn">@T("Admin.Common.SaveContinue")</button>
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}

src/Presentation/SmartStore.Web/Administration/Views/Language/Edit.cshtml
@model LanguageModel
@using Telerik.Web.Mvc.UI
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Languages.EditLanguageDetails").Text;
}
@using (Html.BeginForm())
{
    <div class="section-header">
        <div class="title">
            @T("Admin.Configuration.Languages.EditLanguageDetails") - @Model.Name @Html.ActionLink("(" + T("Admin.Configuration.Languages.BackToList") + ")", "List")
        </div>
        <div class="options">
            <button type="submit" name="save" value="save" class="btn btn-primary"><i class="fa fa-check"></i>&nbsp;@T("Admin.Common.Save")</button>
            <button type="submit" name="save" value="save-continue" class="btn">@T("Admin.Common.SaveContinue")</button>
            <a href="@Url.Action("ExportXml", new { id = Model.Id })" class="btn">@T("Admin.Configuration.Languages.Export")</a>
            <a href="#importxml-window" data-toggle="modal" class="btn">@T("Admin.Configuration.Languages.Import")</a>
            <button type="submit" id="language-delete" class="btn btn-danger"><i class="fa fa-trash-o"></i>&nbsp;@T("Admin.Common.Delete")</button>
        </div>
    </div>
    @Html.Partial("_CreateOrUpdate", Model)
}
@Html.DeleteConfirmation("language-delete")
@*import resources form*@
@{Html.SmartStore().Window()
        .Name("importxml-window")
        .Title(T("Admin.Configuration.Languages.Import").Text)
        .Content(@<text>
    @using (Html.BeginForm("ImportXml", "Language", new { id = Model.Id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div style="margin-bottom: 8px">
            <strong>@T("Admin.Configuration.Languages.XmlFile"):</strong> <input type="file" id="importxmlfile" name="importxmlfile" />
        </div>

        <label class="radio">
            @Html.RadioButton("mode", "3", true, new { id = "importxmlmode_3" })
            @T("Admin.Configuration.Languages.Import.InsertUpdate")
        </label>
        <label class="radio">
            @Html.RadioButton("mode", "1", false, new { id = "importxmlmode_1" })
            @T("Admin.Configuration.Languages.Import.Insert")
        </label>
        <label class="radio">
            @Html.RadioButton("mode", "2", false, new { id = "importxmlmode_2" })
            @T("Admin.Configuration.Languages.Import.Update")
        </label>
        <hr />
        <label class="checkbox">
            @Html.CheckBox("updatetouched", false, new { id = "importxmlupdatetouched" })
            <span class="caption">@T("Admin.Configuration.Languages.Import.UpdateTouched")</span>
        </label>
        
    }
    </text>)
    .FooterContent(@<text>
        <button id="importxmlsubmit" type="button" class="btn btn-primary">@T("Admin.Configuration.Languages.Import")</button>
        <a href="#" class="btn btn-link" data-dismiss="modal">@T("Common.Cancel")</a>
    </text>)
        .Width(400)
        .Modal(true)
        .Visible(false)
        .Render();
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#importxmlsubmit").click(function (e) {
            e.preventDefault();
            $('#importxml-window').find("form").submit();
        });

        $("#importxml-window input[name=mode]").on("change", function (e) {
            var id = $(this).attr("id");
            var chk = $("#importxmlupdatetouched");
            if (id == "importxmlmode_1") {
                chk.attr("disabled", "true").parent().find(">span").addClass("muted");
            }
            else {
                chk.removeAttr("disabled").parent().find(">span").removeClass("muted");
            }
        });
    });

</script>

src/Presentation/SmartStore.Web/Administration/Views/Language/List.cshtml
@model Telerik.Web.Mvc.GridModel<LanguageModel>
@using Telerik.Web.Mvc.UI
@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Languages").Text;
}
<div class="section-header">
    <div class="title">
        <i class="fa fa-language"></i>
        @T("Admin.Configuration.Languages")
    </div>
    <div class="options">
        <a href="@Url.Action("Create")" class="btn btn-primary"><i class="fa fa-plus"></i>&nbsp;@T("Admin.Common.AddNew")</a>
    </div>
</div>
<table class="adminContent">
    <tr>
        <td>
            @(Html.Telerik().Grid<LanguageModel>()
                    .Name("languages-grid")
                    .BindTo(Model.Data)
                    .Columns(columns =>
                    {
                        columns.Bound(x => x.Name)
                            .Template(x => Html.ActionLink(x.Name, "Edit", new { id = x.Id }));
                        columns.Bound(x => x.LanguageCulture)
                            .Width(150)
                            .Centered();
                        columns.Template(
                                @<div>
                                    @Html.ActionLink(T("Admin.Configuration.Languages.Resources.View").Text, "Resources", new { languageId = item.Id })
                                </div>
                            ).Width(200)
                            .Centered()
                            .Title(T("Admin.Configuration.Languages.Resources.View").Text);
                        columns.Bound(x => x.DisplayOrder)
                            .Width(100)
                            .Centered();
                        columns.Bound(x => x.Published)
                            .Width(100)
                            .Template(item => @Html.SymbolForBool(item.Published))
                            .ClientTemplate(@Html.SymbolForBool("Published"))
                            .Centered();
                    })
                    //.DataBinding(dataBinding => dataBinding.Ajax().Select("List", "Language"))
                    .EnableCustomBinding(false))
        </td>
    </tr>
</table>

src/Presentation/SmartStore.Web/Administration/Views/Language/Resources.cshtml
@model Telerik.Web.Mvc.GridModel<LanguageResourceModel>
@using Telerik.Web.Mvc.UI;
@using System.Linq;
@{
    var gridPageSize = EngineContext.Current.Resolve<SmartStore.Core.Domain.Common.AdminAreaSettings>().GridPageSize;
    //page title
    ViewBag.Title = T("Admin.Configuration.Languages.Localization").Text;
}
<div class="section-header">
    <div class="title">
        @T("Admin.Configuration.Languages.Localization")
    </div>
</div>
@if (ViewBag.AllLanguages != null)
{
    <table class="adminContent" style="margin-bottom: 10px;">
        <tr>
            <td class="adminTitle">
                @T("Admin.Configuration.Languages.Select")
            </td>
            <td class="adminData">

	            @Html.DropDownList("localeresource-language", (IEnumerable<SelectListItem>)ViewBag.AllLanguages, new { onchange = "onLocaleResourceLanguageSelected(this.value);" })

                <script type="text/javascript">
                    function onLocaleResourceLanguageSelected(languageid) {
	                    window.location = '@(Url.Action("Resources") + "?languageId=")' + languageid;
	                }
                </script>
            </td>
        </tr>
    </table>
}
<table class="adminContent">
    <tr>
        <td>
            <div class="alert alert-info fade in">
                @T("Admin.Configuration.Languages.Resources.Description")
                <button class="close" data-dismiss="alert">x</button>
            </div>          
        </td>
    </tr>
    <tr>
        <td>
            @(Html.Telerik().Grid<LanguageResourceModel>()
                    .Name("resources-grid")
                    .DataKeys(x =>
                    {
                        x.Add(y => y.Id).RouteKey("Id");
                        x.Add(y => y.LanguageId).RouteKey("languageId");
                    })
                    .Columns(columns =>
                    {
                        columns.Bound(x => x.LanguageName)
                            .Width("10%")
                            .ReadOnly()
                            .Filterable(false);
                        columns.Bound(x => x.Name).Width("30%");
                        columns.Bound(x => x.Value).EditorTemplateName("MultilineText").Width("60%");
                        columns.Command(commands =>
                        {
                            commands.Edit().Localize(T);
                            commands.Delete().Localize(T);
                        });

                    })
                    .ToolBar(x => x.Insert())
                    .Editable(x =>
                    {
                        x.Mode(GridEditMode.InLine);
                    })
                    .Filterable()
                    .Pageable(settings => settings.PageSize(gridPageSize).Total(Model.Total).Position(GridPagerPosition.Both))
                    .DataBinding(dataBinding =>
                    {
                        dataBinding.Ajax().Select("Resources", "Language")
                            .Update("ResourceUpdate", "Language")
                            .Delete("ResourceDelete", "Language")
                            .Insert("ResourceAdd", "Language", new { id = ViewBag.LanguageId });
                    })
                    .EnableCustomBinding(true)
                    .ClientEvents(x => x.OnEdit("onResourceEdit"))
                    .ClientEvents(x => x.OnError("Grid_onError")))
        </td>
    </tr>
</table>
<script type="text/javascript">
    function onResourceEdit(e) {
        if (e.mode == "insert") {
            $(e.form).find("td:first").html("@ViewBag.LanguageName");
        }
    }
    function Grid_onError(e) {
        alert(e.XMLHttpRequest.responseText);
        e.preventDefault();
    }
</script>

src/Presentation/SmartStore.Web/Administration/Views/Language/_CreateOrUpdate.cshtml
@model LanguageModel

@using Telerik.Web.Mvc.UI;
@using SmartStore.Web.Framework.UI;

@Html.ValidationSummary(true)
@Html.HiddenFor(model => model.Id)
@Html.SmartStore().TabStrip().Name("language-edit").Style(TabsStyle.Tabs).Position(TabsPosition.Top).Items(x =>
{
	x.Add().Text(T("Admin.Common.Info").Text).Content(TabInfo()).Selected(true);
	x.Add().Text(T("Admin.Common.Stores").Text).Content(TabStores());

    //generate an event
	EngineContext.Current.Resolve<IEventPublisher>().Publish(new TabStripCreated(x, "language-edit", this.Html, this.Model));
})

@helper TabInfo()
{
	var cultures = System.Globalization.CultureInfo.GetCultures(System.Globalization.CultureTypes.SpecificCultures).ToList();
<script type="text/javascript">
    function toggleFlags() {
        $('#pnlAllFlags').toggle();
        if ($('#pnlAllFlags').css('display') == 'none') {
            $('#displayAllFlags').html('@T("Admin.Common.Show")');
        }
        else {
            $('#displayAllFlags').html('@T("Admin.Common.Hide")');
        }
    }
</script>

<table class="adminContent">
    <tr>
        <td class="adminTitle">
            @Html.SmartLabelFor(model => model.Name)
        </td>
        <td class="adminData">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SmartLabelFor(model => model.LanguageCulture)
        </td>
        <td class="adminData">
            @* codehint: sm-edit *@
            @Html.DropDownListFor(x => x.LanguageCulture, cultures.Select(x => 
                new SelectListItem { Value = x.IetfLanguageTag, Text = string.Format("{0} [{1}]", x.DisplayName, x.IetfLanguageTag) }))
            @Html.ValidationMessageFor(model => model.LanguageCulture)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SmartLabelFor(model => model.UniqueSeoCode)
        </td>
        <td class="adminData">
            @Html.EditorFor(model => model.UniqueSeoCode)
            @Html.ValidationMessageFor(model => model.UniqueSeoCode)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SmartLabelFor(model => model.FlagImageFileName)
        </td>
        <td class="adminData">
            @Html.EditorFor(model => model.FlagImageFileName)
            @Html.ValidationMessageFor(model => model.FlagImageFileName)
            <br/>
            <a id="displayAllFlags" href="javascript:toggleFlags();">@T("Admin.Common.Show")</a>
            <div id="pnlAllFlags" style="display: none">
                @foreach (var fileName in Model.FlagFileNames)
                {
                    <a href="javascript: void(0)" class="flag" data-filename="@fileName">
                        <img alt="" src="@Url.Content("~/Content/Images/flags/" + fileName)"/>
                        @fileName
                        <text>, </text>
                    </a>
                }
            </div>
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SmartLabelFor(model => model.Rtl)
        </td>
        <td class="adminData">
            @Html.EditorFor(model => model.Rtl)
            @Html.ValidationMessageFor(model => model.Rtl)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SmartLabelFor(model => model.Published)
        </td>
        <td class="adminData">
            @Html.EditorFor(model => model.Published)
            @Html.ValidationMessageFor(model => model.Published)
        </td>
    </tr>
    <tr>
        <td class="adminTitle">
            @Html.SmartLabelFor(model => model.DisplayOrder)
        </td>
        <td class="adminData">
            @Html.EditorFor(model => model.DisplayOrder)
            @Html.ValidationMessageFor(model => model.DisplayOrder)
        </td>
    </tr>
</table>
}

@helper TabStores()
{
    <script type="text/javascript">
    	$(document).ready(function () {

    		$("#@Html.FieldIdFor(model => model.LimitedToStores)").click(toggleStoreMapping);

    	    toggleStoreMapping();

    	    $("#pnlAllFlags a.flag").click(function () {
    	        $("#FlagImageFileName").val($(this).data("filename"));
    	    });
        });


        function toggleStoreMapping() {
        	if ($('#@Html.FieldIdFor(model => model.LimitedToStores)').is(':checked')) {
        		$('#pnl-available-stores').show();
        	}
        	else {
        		$('#pnl-available-stores').hide();
        	}
        }

    </script>
    <table class="adminContent">
        <tr>
            <td class="adminTitle">
                @Html.SmartLabelFor(model => model.LimitedToStores)
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.LimitedToStores)
                @Html.ValidationMessageFor(model => model.LimitedToStores)
            </td>
        </tr>
        <tr id="pnl-available-stores">
            <td class="adminTitle">
                @Html.SmartLabelFor(model => model.AvailableStores)
            </td>
            <td class="adminData">
                @if (Model.AvailableStores != null && Model.AvailableStores.Count > 0)
                {
                    foreach (var store in Model.AvailableStores)
                    {
					<label class="checkbox">
						<input type="checkbox" name="SelectedStoreIds" value="@store.Id" checked="@(Model.SelectedStoreIds != null && Model.SelectedStoreIds.Contains(store.Id))" />
						<span>@store.Name</span>
					</label>						
                    }
                }
                else
                {
                    <div>@T("Admin.Configuration.Stores.NoStoresDefined")</div>
                }</td>
        </tr>
    </table>
}